add explicit parens around -> on the constraint
`->` has very low priority so without them Postgres errors out:

django.db.utils.ProgrammingError: operator does not exist: hstore -> boolean

that's because foo->bar IS NOT NULL gets interpreted as foo->(bar IS NOT NULL) which is clearly wrong