Filter out duplicate rows for ConflictAction.NOTHING
We're using a trick to be able to return all rows that you
specified during a bulk_insert even when you use DO NOTHING. However
in order to accomplish this trick, we actually use DO UPDATE. DO UPDATE
barfs at duplicate rows:

django.db.utils.ProgrammingError: ON CONFLICT DO UPDATE command cannot affect row a second time
HINT:  Ensure that no rows proposed for insertion within the same command have duplicate constrained values.

In order to make sure ConflictAction.NOTHING works as people expect
it to work, we filter out duplicate rows before attempting the query.